### ISSUE TITLE
Wrong bem transform.

### ISSUE THREAD

**Issue by dimensi** [emmetio/html-transform#11]
Not working cases like this

|Value|Result|Expect
|--|--|--|
|.block>.-element-name  |`<div class="block"><div class="block__element"></div></div>`  | `<div class="block"><div class="block__element-name"></div></div>` |
|.block>.-element_mod-val|`<div class="block"><div class="block__element block__element--mod"></div></div>`|`<div class="block"><div class="block__element block__element--mod_val"></div></div>`|

Return please `bem.shortElementPrefix` options. I want **DISABLE THIS**!!!
In old version emmet in vs code emmet bem was good tool, now this tool for tortule.

**Comment by dimensi** [comment]
@ramya-rao-a this cases not work in 1.9.3 vs code.

**Comment by dimensi** [comment]
I check library directly, only second case not work. I can't set options for modificator.

**Comment by ramya-rao-a** [comment]
@edDimensi The first case works as you expect in the latest Insiders as mentioned in https://github.com/emmetio/html-transform/issues/3#issuecomment-361039639

For your second case, I get the below in the latest Insiders

```
<div class="block">
    <div class="block__element block__element_mod-val"></div>
</div>
```
 which matches with what is shown in https://docs.emmet.io

![emmetbem](https://user-images.githubusercontent.com/16890566/35479374-d9d69bc6-03aa-11e8-93e3-1e7d70084e12.gif)

About your point on bem options. Below are the 3 documented for emmet

<img width="490" alt="screen shot 2018-01-27 at 9 44 18 pm" src="https://user-images.githubusercontent.com/16890566/35479396-4e682cfc-03ab-11e8-8dd6-1d2a63d60cd4.png">

of which the first 2 are supported in VS Code. Use the setting `emmet.preferences`

I don't see a lot of use for the 3rd one i.e the `bem.shortElementPrefix`. Can you elaborate on how that would help you?

**Comment by dimensi** [comment]
@ramya-rao-a, I dont wan't use shortPrefixes!
My bem notation looks like this
`block-name__element-name--mod_val`  
And the fact that the bottom dash is a modifier, and the upper dash is an element, this introduces me into a stupor.
In old versions i simple disable this feature and use full prefixes.
P.S. You are sure emmet version on docs.emmet.io is actual version? I test library directly and second case not working.

**Comment by ramya-rao-a** [comment]
> In old versions i simple disable this feature and use full prefixes.

How were you disabling this feature?

> I test library directly and second case not working.

Which library are you testing directly?

**Comment by dimensi** [comment]
@ramya-rao-a 
> bem.shortElementPrefix
> Symbol for describing short “block-element” notation. Class names prefixed with this symbol will be treated as element name for parent‘s block name. Each symbol instance traverses one level up in parsed tree for block name lookup. Empty value will disable short notation.  

from [emmet docs](https://docs.emmet.io/customization/preferences/).


I test this html-transform in [repl.it](https://repl.it/@eddimensi/NavajowhiteParchedIndigowingedparrot)
P.S. Sorry for long answer and i want disable shortElementPrefix only for my bem style.
`block-name__element-name--mod_value`.

**Comment by ramya-rao-a** [comment]
@edDimensi I still dont understand how were you disabling the shortElementPrefix feature before?

**Comment by dimensi** [comment]
@ramya-rao-a before vs code update emmet to 2.0.  I cound set in
```
  "emmet.preferences": {
    "bem.shortElementPrefix: "",
  },
```
this and shortElementPrefix go to off.

**Comment by ramya-rao-a** [comment]
@edDimensi I downloaded the old VS code from https://code.visualstudio.com/updates/v1_10 which has the old emmet

With 
```
  "emmet.preferences": {
        "bem.shortElementPrefix": ""
    }
```

`.block>.-element_mod-val` expands to 
```
<div class="block">
        <div class="-element -element_mod-val"></div>
    </div>
```

But in https://github.com/emmetio/html-transform/issues/11#issue-292156191 you are saying that it should expand to 

```
<div class="block">
     <div class="block__element block__element--mod_val"></div>
</div>
```

**Comment by dimensi** [comment]
@ramya-rao-a  in this case you must write full prefixes
`.block>.__element--mod-val` and i want this behavior

**Comment by ramya-rao-a** [comment]
In old emmet, with shortElemetPrefix disabled, `.block>.__element--mod-val` expands to 
```
<div class="block">
        <div class="block__element--mod-val"></div>
    </div>
``` 

and not

```
<div class="block">
     <div class="block__element block__element--mod_val"></div>
</div>
```

**Comment by dimensi** [comment]
@ramya-rao-a, sorry my mistake
`.block>.__element.--mod_val`

**Comment by ramya-rao-a** [comment]
That expands to 
```
<div class="block">
        <div class="block__element --mod-val"></div>
    </div>
```

**Comment by dimensi** [comment]
@ramya-rao-a you're sure to set this settings?
```  "emmet.preferences": {
    "bem.elementSeparator": "__",
    "bem.modifierSeparator": "--",
    "bem.shortElementPrefix: "",
  },
```

**Comment by ramya-rao-a** [comment]
:) you never mentioned the other 2 settings

Now with that we get the below in old emmet
```
<div class="block">
        <div class="block__element block block--mod-val"></div>
    </div>
```

**Comment by ramya-rao-a** [comment]
That still doesnt look like what you were expecting

**Comment by dimensi** [comment]
How me get vs code 1.10 ?

**Comment by ramya-rao-a** [comment]
Download from https://code.visualstudio.com/updates/v1_10

**Comment by dimensi** [comment]
@ramya-rao-a i get what i want.
`.block>.__element--mod_val` transforms to 
```
<div class="block">
  <div class="block__element block__element--mod_val"></div>
</div>
```
![vokoscreen-2018-02-10_03-05-43](https://user-images.githubusercontent.com/11390039/36055703-58b5e9f6-0e0f-11e8-9f6f-3ac97d377432.gif)
in new emmet i can't get this result.

Oh god, it's work beatiful! I really want this behavior.

**Comment by ramya-rao-a** [comment]
Great, now we have a good starting point. I'll dig deeper with this example and get back in a few days

**Comment by dimensi** [comment]
Thank you very much!

**Comment by ramya-rao-a** [comment]
@sergeche Before I jump into this, I wanted to confirm with you if this expectation in the old emmet is valid to begin with.

Preferences:
```
  "bem.elementSeparator": "__",
    "bem.modifierSeparator": "--",
    "bem.shortElementPrefix:: "",
```

Abbreviation: `.block>.__element--mod_val`
Expected expansion: 
```
<div class="block">
  <div class="block__element block__element--mod_val"></div>
</div>
```

**Comment by dimensi** [comment]
@ramya-rao-a any news?

**Comment by ramya-rao-a** [comment]
@dimensi Sorry, I havent been able to work on this. I would ask @sergeche for his thoughts on https://github.com/emmetio/html-transform/issues/11#issuecomment-364606600

**Comment by sergeche** [comment]
@ramya-rao-a Sorry, been to busy. No, these options are used for output only. Input syntax should remain the same (`.block>.-element_mod_val`)

**Comment by ramya-rao-a** [comment]
@sergeche isn't `bem.shortElementPrefix`used in the input?

**Comment by sergeche** [comment]
Yes, `bem.shortElementPrefix` is used to modify input, e.g. instead of `-elem` write something else. I don’t think this option is valuable so it can be simply ignored
