### ISSUE TITLE
$ in abbreviations without repeater should get replaced with 1

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/html-transform#17]
According to https://github.com/emmetio/html-transform/blob/v0.3.10/test/numbering.js#L13-L15, the `$` in abbreviations without explicit repeaters are not expected to be replaced with numbers.

But in https://docs.emmet.io/, it does get replaced with 1. For example:  `p{$}` expands to `<p>1</p>`

cc @sergeche

**Comment by sergeche** [comment]
This is intended behaviour in new version: lots of people had to escape `$` too often, especially in PHP
