### ISSUE TITLE
Customizing bem modifier doesnt work as expected

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/html-transform#4]
`.hello_mod1._mod2` and `.hello._mod1._mod2` both expand to `<div class="hello hello_mod1 hello_mod2"></div>` as expected

Now update the options so that the `modifier` is `__`

Now `.hello_mod1._mod2` incorrectly expands to  `<div class="hello_mod1 hello_mod1__mod2"></div>`

`.hello._mod1._mod2` correctly expands to `<div class="hello hello__mod1 hello__mod2"></div>`

cc @sergeche

**Comment by sergeche** [comment]
`modifier` is for output, not for input. Input notation must be the same

**Comment by ramya-rao-a** [comment]
@sergeche Input notations are the same

`.hello_mod1._mod2` and `.hello._mod1._mod2` should both expand to the exact same output.

They do expand to the exact the same output by default.

But when you change the `modifier` option to `__` in the options when calling the `expand` method from the `expand-abbreviation` module, you get different output for the 2

**Comment by ramya-rao-a** [comment]
For a simpler example, take your test cases
https://github.com/emmetio/html-transform/blob/v0.3.5/test/bem.js#L13-L14

They both give the same output. This is because of [`expandClassNames`](https://github.com/emmetio/html-transform/blob/v0.3.5/lib/addons/bem.js#L38) makes sure that the class "b" gets applied in the first test case. 

Now from what I understand the `modifier` option at https://github.com/emmetio/html-transform/blob/v0.3.5/lib/addons/bem.js#L5 should be used for output

But in https://github.com/emmetio/html-transform/blob/v0.3.5/lib/addons/bem.js#L41, you use it to scan the input. This is the root cause of the issue I have logged here.

**Comment by dimensi** [comment]
I have problem with expand.
`.test.-test._test-key` -> `<div class="test test__test test--test"></div>`
I wait this `<div class="test test__test test--test-key"></div>`
and i can't use structure like this
`.test.-test._test_key`

**Comment by ramya-rao-a** [comment]
@edDimensi Please log a new issue in this repo for the issue you are seeing. In the new issue, also specify if you have customized the bem.elementSeparator or bem.modifierSeparator settings
